//! Compatibility manifest v1: parse + verify.
//!
//! The manifest is generated by staging (`stage-runtime.ps1`, owned by
//! RuntimePackaging). [`CompatManifest::verify`] checks target, exact version
//! strings, the `node.exe` SHA-256, and the deterministic payload tree hash
//! BEFORE any process creation.

use std::path::Path;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::compatibility::{
    CONTROLLER_VERSION, DISTRIBUTION_VERSION, DSH_VERSION, NODE_VERSION, PNPM_VERSION, TARGET,
};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NodeManifest {
    pub version: String,
    pub sha256: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CompatManifest {
    pub schema_version: u32,
    pub protocol_version: u32,
    pub controller_version: String,
    pub node: NodeManifest,
    pub pnpm_version: String,
    pub distribution_version: String,
    pub dsh_version: String,
    pub target: String,
    pub payload_sha256: String,
}

impl CompatManifest {
    /// Parse and validate the closed enum/version fields. Extra fields are
    /// rejected by `deny_unknown_fields`.
    pub fn parse(json: &str) -> Result<Self, String> {
        let m: CompatManifest =
            serde_json::from_str(json).map_err(|e| format!("invalid manifest: {e}"))?;
        if m.schema_version != 1 {
            return Err("schemaVersion must be 1".to_string());
        }
        if m.protocol_version != 1 {
            return Err("protocolVersion must be 1".to_string());
        }
        let checks: [(&str, &str); 5] = [
            ("controllerVersion", &m.controller_version),
            ("node.version", &m.node.version),
            ("pnpmVersion", &m.pnpm_version),
            ("distributionVersion", &m.distribution_version),
            ("dshVersion", &m.dsh_version),
        ];
        let expected = [
            CONTROLLER_VERSION,
            NODE_VERSION,
            PNPM_VERSION,
            DISTRIBUTION_VERSION,
            DSH_VERSION,
        ];
        for ((field, actual), want) in checks.iter().zip(expected.iter()) {
            if actual != want {
                return Err(format!("{field} mismatch: got {actual}, want {want}"));
            }
        }
        if m.target != TARGET {
            return Err(format!("target mismatch: got {}, want {TARGET}", m.target));
        }
        Ok(m)
    }

    /// Verify target/versions (asserted in `parse`), `node.exe` SHA-256, and the
    /// deterministic payload tree hash against the staged runtime directory.
    pub fn verify(&self, payload_dir: &Path) -> Result<(), String> {
        // Re-assert the closed version fields (defense in depth).
        if self.target != TARGET {
            return Err(format!("target mismatch: {}", self.target));
        }

        let node_exe = payload_dir.join("node").join("node.exe");
        let node_bytes = std::fs::read(&node_exe).map_err(|e| format!("read node.exe: {e}"))?;
        let node_hash = sha256_hex(&node_bytes);
        if !node_hash.eq_ignore_ascii_case(&self.node.sha256) {
            return Err(format!(
                "node.exe sha256 mismatch: got {node_hash}, manifest {}",
                self.node.sha256
            ));
        }

        let actual_payload = payload_tree_hash(payload_dir)?;
        if !actual_payload.eq_ignore_ascii_case(&self.payload_sha256) {
            return Err(format!(
                "payload sha256 mismatch: got {actual_payload}, manifest {}",
                self.payload_sha256
            ));
        }
        Ok(())
    }
}

/// Authenticate the raw external `manifest.json` text against an independently
/// pinned SHA-256 digest (computed by `build.rs` after staging) BEFORE any of
/// its fields — including the self-described `node.sha256` and `payloadSha256`
/// — are trusted. A replaced manifest fails here even when its self-described
/// hashes are internally consistent with a modified payload.
pub fn verify_manifest_digest(json: &str, expected_sha256: &str) -> Result<(), String> {
    if expected_sha256.is_empty() {
        return Err("manifest digest not pinned at build time".to_string());
    }
    let actual = sha256_hex(json.as_bytes());
    if !actual.eq_ignore_ascii_case(expected_sha256) {
        return Err(format!(
            "manifest digest mismatch: got {actual}, expected {expected_sha256}"
        ));
    }
    Ok(())
}

/// Deterministic payload tree hash: over every file under `root` EXCEPT
/// `manifest.json`, compute `record = SHA256(file) || relpath_utf8 || 0x00`,
/// sort records ascending by `relpath_utf8` (UTF-8, `/` separators), then
/// `SHA256(concat(records))`, hex-lowercased.
fn payload_tree_hash(root: &Path) -> Result<String, String> {
    let mut files: Vec<String> = Vec::new();
    collect_files(root, root, &mut files)?;
    let mut records: Vec<(String, Vec<u8>)> = Vec::new();
    for rel in files {
        let data = std::fs::read(root.join(&rel)).map_err(|e| format!("read {rel}: {e}"))?;
        let mut record = Vec::with_capacity(32 + rel.len() + 1);
        record.extend_from_slice(&sha256_raw(&data));
        record.extend_from_slice(rel.as_bytes());
        record.push(0);
        records.push((rel, record));
    }
    records.sort_by(|a, b| a.0.cmp(&b.0));
    let mut concat = Vec::new();
    for (_, rec) in records {
        concat.extend_from_slice(&rec);
    }
    Ok(hex_lower(&sha256_raw(&concat)))
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<String>) -> Result<(), String> {
    let entries = std::fs::read_dir(dir).map_err(|e| format!("read_dir {}: {e}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("read_dir entry: {e}"))?;
        let path = entry.path();
        let rel = path
            .strip_prefix(root)
            .map_err(|e| format!("strip_prefix: {e}"))?;
        let rel_str = rel.to_string_lossy().replace('\\', "/");
        let is_dir = entry
            .file_type()
            .map_err(|e| format!("file_type: {e}"))?
            .is_dir();
        if is_dir {
            collect_files(root, &path, out)?;
        } else if rel_str != "manifest.json" {
            out.push(rel_str);
        }
    }
    Ok(())
}

fn sha256_raw(data: &[u8]) -> [u8; 32] {
    let digest = Sha256::digest(data);
    let mut out = [0u8; 32];
    out.copy_from_slice(digest.as_slice());
    out
}

fn sha256_hex(data: &[u8]) -> String {
    hex_lower(&sha256_raw(data))
}

fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        s.push(HEX[(b >> 4) as usize] as char);
        s.push(HEX[(b & 0xf) as usize] as char);
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest_json() -> String {
        format!(
            "{{\"schemaVersion\":1,\"protocolVersion\":1,\"controllerVersion\":\"{CONTROLLER_VERSION}\",\"node\":{{\"version\":\"{NODE_VERSION}\",\"sha256\":\"{}\"}},\"pnpmVersion\":\"{PNPM_VERSION}\",\"distributionVersion\":\"{DISTRIBUTION_VERSION}\",\"dshVersion\":\"{DSH_VERSION}\",\"target\":\"{TARGET}\",\"payloadSha256\":\"{}\"}}",
            "0".repeat(64),
            "0".repeat(64),
        )
    }

    #[test]
    fn parse_accepts_exact_field_set() {
        let m = CompatManifest::parse(&manifest_json()).unwrap();
        assert_eq!(m.schema_version, 1);
        assert_eq!(m.controller_version, CONTROLLER_VERSION);
        assert_eq!(m.node.version, NODE_VERSION);
        assert_eq!(m.dsh_version, DSH_VERSION);
    }

    #[test]
    fn parse_rejects_extra_field() {
        let mut v: serde_json::Value = serde_json::from_str(&manifest_json()).unwrap();
        v["extra"] = serde_json::json!(true);
        assert!(CompatManifest::parse(&v.to_string()).is_err());
    }

    #[test]
    fn parse_rejects_wrong_version() {
        let bad = manifest_json().replace(NODE_VERSION, "99.99.99");
        assert!(CompatManifest::parse(&bad).is_err());
    }

    #[test]
    fn parse_rejects_wrong_target() {
        let bad = manifest_json().replace(TARGET, "aarch64-apple-darwin");
        assert!(CompatManifest::parse(&bad).is_err());
    }

    #[test]
    fn sha256_known_vector() {
        // SHA-256 of empty input.
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
    }

    #[test]
    fn payload_tree_hash_is_deterministic_and_excludes_manifest() {
        let dir =
            std::env::temp_dir().join(format!("pimp-dsh-payload-test-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("sub")).unwrap();
        std::fs::write(dir.join("manifest.json"), b"ignored").unwrap();
        std::fs::write(dir.join("a.txt"), b"alpha").unwrap();
        std::fs::write(dir.join("sub").join("b.txt"), b"beta").unwrap();
        let h1 = payload_tree_hash(&dir).unwrap();
        let h2 = payload_tree_hash(&dir).unwrap();
        assert_eq!(h1, h2, "deterministic");
        // Changing manifest.json must not change the payload hash.
        std::fs::write(dir.join("manifest.json"), b"changed").unwrap();
        assert_eq!(payload_tree_hash(&dir).unwrap(), h1);
        // Changing a real payload file must change the hash.
        std::fs::write(dir.join("a.txt"), b"gamma").unwrap();
        assert_ne!(payload_tree_hash(&dir).unwrap(), h1);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn verify_manifest_digest_authenticates_before_trust() {
        let json = r#"{"schemaVersion":1,"payloadSha256":"00"}"#;
        let digest = sha256_hex(json.as_bytes());
        assert!(
            verify_manifest_digest(json, &digest).is_ok(),
            "the exact pinned bytes must authenticate"
        );
        // A replaced manifest — even one whose self-described hashes are
        // internally consistent — must fail the independently pinned digest.
        let replaced = r#"{"schemaVersion":1,"payloadSha256":"11"}"#;
        assert!(
            verify_manifest_digest(replaced, &digest).is_err(),
            "a replaced manifest must not authenticate against the old digest"
        );
        // An unpinned digest must fail closed.
        assert!(
            verify_manifest_digest(json, "").is_err(),
            "an unpinned manifest digest must fail closed"
        );
    }
}
