//! Windows real-runtime closure probe (packaged staging slice).
//!
//! Resolves the canonical staged runtime (`apps/desktop/src-tauri/runtime`,
//! generated by `scripts/stage-runtime.ps1`) through [`PackagedProvider`],
//! stages that full verified Node 24.19.0 + DSH rc.7 payload into a fresh
//! AppContainer private root with [`Confinement::stage_runtime`] — which
//! re-verifies source AND destination through the shared compatibility helper
//! and rejects reparse points — then executes the real staged CLI twice via
//! `Job::create_suspended_with`: `help` (static usage, exit 0) and a bounded
//! offline `doctor --json` (structured schema output, no update-check/network).
//!
//! The probe is skipped when the large generated runtime is absent so the
//! regular CI stays green. Run it on a machine with a staged runtime:
//!
//! ```powershell
//! scripts/stage-runtime.ps1
//! pnpm -C apps/desktop desktop:test
//! ```

#![cfg(windows)]

use std::ffi::OsString;
use std::io;
use std::path::{Path, PathBuf};
use std::time::Duration;

use pimp_dsh_desktop::compatibility::{LaunchSpec, PackagedProvider, Provider};
use pimp_dsh_desktop::confinement::Confinement;
use pimp_dsh_desktop::job::{ChildGuard, FileHandle, Job};

/// Drain a pipe to EOF and return its text. Bounded by the caller's exit /
/// termination window, never by unbounded reads.
fn drain(pipe: &Option<FileHandle>) -> String {
    let mut bytes = Vec::new();
    if let Some(pipe) = pipe {
        let mut buf = [0u8; 256];
        loop {
            match pipe.read(&mut buf) {
                Ok(0) | Err(_) => break,
                Ok(count) => bytes.extend_from_slice(&buf[..count]),
            }
        }
    }
    String::from_utf8_lossy(&bytes).into_owned()
}

/// RAII profile guard: always removes the private AppContainer profile and
/// its root, on the success path AND every failure path that reaches a
/// created [`Confinement`] (an `expect`/`assert` abort still drops it).
struct ProbeApp {
    confinement: Confinement,
    private_root: PathBuf,
}

impl ProbeApp {
    fn create() -> Self {
        let confinement = Confinement::create().expect("create the AppContainer profile");
        let private_root = confinement.private_root().to_path_buf();
        ProbeApp {
            confinement,
            private_root,
        }
    }

    fn conf(&self) -> &Confinement {
        &self.confinement
    }

    fn private_root(&self) -> &Path {
        &self.private_root
    }

    fn cleanup(&mut self) -> io::Result<()> {
        self.confinement.cleanup()
    }
}

impl Drop for ProbeApp {
    fn drop(&mut self) {
        let _ = self.confinement.cleanup();
    }
}

/// Rewrite a staged spec to a specific CLI command (e.g. `help` or
/// `doctor --json`), keeping the private-root executable/cwd and environment.
fn probe_spec(staged: &LaunchSpec, command: Vec<OsString>) -> LaunchSpec {
    LaunchSpec {
        node_exe: staged.node_exe.clone(),
        cli_entry: staged.cli_entry.clone(),
        cwd: staged.cwd.clone(),
        env: staged.env.clone(),
        args: command,
    }
}

/// Run a suspended staged child under the Job + AppContainer: assign before
/// resume, wait bounded by `timeout`, terminate through the Job if the real
/// CLI exceeds it, then drain both pipes. Returns (exit code, stdout, stderr).
fn run_probe(
    job: &Job,
    app: &LaunchSpec,
    confinement: &Confinement,
    timeout: Duration,
    label: &str,
) -> (Option<u32>, String, String) {
    let child = job
        .create_suspended_with(app, Some(confinement))
        .unwrap_or_else(|error| panic!("{label}: spawn the staged CLI: {error}"));
    let guard = ChildGuard::new(child);
    job.assign(guard.child())
        .unwrap_or_else(|error| panic!("{label}: assign before resume: {error}"));
    job.resume(guard.child())
        .unwrap_or_else(|error| panic!("{label}: resume: {error}"));
    let child = guard.into_inner();
    let code = match child
        .process
        .wait_timeout(timeout)
        .unwrap_or_else(|error| panic!("{label}: wait for the real CLI: {error}"))
    {
        Some(code) => Some(code),
        None => {
            let _ = job.terminate();
            child
                .process
                .wait_timeout(Duration::from_secs(3))
                .unwrap_or_else(|error| panic!("{label}: terminate bound: {error}"))
        }
    };
    (code, drain(&child.stdout), drain(&child.stderr))
}

#[test]
fn staged_real_runtime_runs_help_and_offline_doctor() {
    // Large generated-runtime gate: a host without the staged payload skips
    // the probe (the regular contract suite stays green). Stage it first:
    //   scripts/stage-runtime.ps1
    //   pnpm -C apps/desktop desktop:test
    let source_manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("runtime")
        .join("manifest.json");
    if !source_manifest.is_file() {
        println!(
            "SKIP runtime probe: apps/desktop/src-tauri/runtime/manifest.json not staged; run scripts/stage-runtime.ps1 first"
        );
        return;
    }

    let provider = PackagedProvider::new(PathBuf::from(env!("CARGO_MANIFEST_DIR")));
    let source = provider
        .resolve()
        .expect("resolve the verified packaged runtime");

    let mut scope = ProbeApp::create();
    let staged = scope
        .conf()
        .stage_runtime(&source)
        .expect("stage the verified runtime into the private root");

    // The AppContainer capabilities descriptor must be empty (zero SIDs), so
    // the child runs only on the profile's own default read grants.
    let caps = unsafe { *scope.conf().security_capabilities_ptr() };
    assert_eq!(
        caps.CapabilityCount, 0,
        "zero capabilities descriptor expected"
    );
    assert!(
        !caps.AppContainerSid.is_null(),
        "a real profile SID must back the descriptor"
    );

    let job = Job::new().expect("Job::new");

    // `help`: static usage line, exit 0, no network/updater touch.
    let (code, stdout, stderr) = run_probe(
        &job,
        &probe_spec(&staged, vec![OsString::from("help")]),
        scope.conf(),
        Duration::from_secs(20),
        "help",
    );
    assert_eq!(
        code,
        Some(0),
        "staged `help` must exit 0 (stderr: {stderr})"
    );
    assert!(
        stdout.contains("doctor"),
        "`help` must list the command set: {stdout}"
    );
    assert!(
        !stderr.contains("update"),
        "`help` must not touch the updater: {stderr}"
    );
    // `doctor --json --runtime-only`: bounded structured diagnostics for the
    // real Node + DSH closure. Host PowerShell/ACL probes are deliberately
    // omitted because they are outside the AppContainer runtime boundary.
    let (code, stdout, _stderr) = run_probe(
        &job,
        &probe_spec(
            &staged,
            vec![
                OsString::from("doctor"),
                OsString::from("--json"),
                OsString::from("--runtime-only"),
            ],
        ),
        scope.conf(),
        Duration::from_secs(20),
        "doctor",
    );
    assert_eq!(
        code,
        Some(0),
        "staged `doctor --json` must exit 0 (stdout: {stdout}; stderr: {_stderr})"
    );
    let parsed: serde_json::Value = serde_json::from_str::<serde_json::Value>(stdout.trim())
        .expect("doctor stdout must be valid structured JSON: {stdout}");
    assert_eq!(parsed["schemaVersion"].as_u64().unwrap_or_default(), 1);
    assert_eq!(parsed["command"].as_str().unwrap_or_default(), "doctor");
    assert!(
        !stdout.contains("updateAvailable"),
        "an offline doctor must not run the update-check: {stdout}"
    );

    scope
        .cleanup()
        .expect("remove the private profile after a successful probe");
    assert!(
        !scope.private_root().exists(),
        "the private profile root must be absent after cleanup"
    );
}

#[test]
fn stage_runtime_rejects_a_workspace_source_and_still_cleans_up() {
    let mut scope = ProbeApp::create();
    // A DevProvider-shaped source: absolute workspace CLI entry, workspace cwd,
    // no packaged manifest at the payload root. Staging must reject it without
    // copying any bytes, and cleanup must still remove the profile.
    let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("..");
    let source = LaunchSpec {
        node_exe: workspace.join("node").join("node.exe"),
        cli_entry: workspace.join("dist").join("cli.js"),
        cwd: workspace,
        env: Vec::new(),
        args: Vec::new(),
    };
    assert!(
        scope.conf().stage_runtime(&source).is_err(),
        "a workspace/DevProvider-shaped source must be rejected, not copied"
    );
    scope
        .cleanup()
        .expect("cleanup after a rejected staging source");
    assert!(
        !scope.private_root().exists(),
        "rejected staging must still remove the private profile root"
    );
}
